version: '3.7'
services:
  frontend:
    container_name: front-quevotan:v2
    build: ./
    restart: always
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 1080:1080
    stdin_open: true
    command: npm start