version: '3.7'
services:
  frontend:
    container_name: front-quevotan-2.0
    build: ./
    restart: always
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 8081:1080
    stdin_open: true
    command: npm start